# Generated by Django 2.2.2 on 2019-07-03 02:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='nationality',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quizuser',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizapp.UserNations'),
        ),
    ]
