# Generated by Django 2.2.2 on 2019-07-03 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_auto_20190703_0243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizuser',
            name='nationality',
            field=models.IntegerField(),
        ),
    ]
