# Generated by Django 2.2.2 on 2019-06-27 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0002_qualifydegree_quiz_quizanswer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='answer',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='inputopt',
            field=models.IntegerField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quizanswer',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
