# Generated by Django 2.2.2 on 2019-06-28 04:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0003_auto_20190627_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qualification',
            name='degree',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizapp.QualifyDegree'),
        ),
    ]
