# Generated by Django 2.2.2 on 2019-07-02 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quizapp', '0004_auto_20190628_0448'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizuser',
            name='profilepic',
            field=models.ImageField(default='dsadfsadf', upload_to='profile'),
            preserve_default=False,
        ),
    ]
